### ISSUE TITLE
Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce-api-docs#1]
@claudiosanches I have tested this repo with PHP 7.2 and received the following error:

```
Fatal error: Cannot use 'Object' as class name as it is reserved in /var/www/html/apigen/vendor/latte/latte/src/Latte/Object.php on line 14 ErrorException: Cannot use 'Object' as class name as it is reserved in /var/www/html/apigen/vendor/latte/latte/src/Latte/Object.php:14
```

**Comment by claudiosanches** [comment]
Will not work in PHP 7.2, since ApiGen doesn't support it. Closing since we probably will start trying to look for a new library.

**Comment by shivapoudel** [comment]
@claudiosanches Have you found any new library to replace ApiGen to support the latest PHP versions?

**Comment by claudiosanches** [comment]
@shivapoudel I just updated this project now using PHPDoc RC, now works just fine.

**Comment by shivapoudel** [comment]
@claudiosanches While executing `./deploy.sh -s 4.3.3 --build-only` command, I am receiving this error:

![image](https://user-images.githubusercontent.com/3774827/90573525-5c89b100-e1d6-11ea-9f06-e6658a00eaf6.png)
